//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetAdapterController.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetAdapterController.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disconnected.
        /// </summary>
        internal static string NetConnectionStatus0 {
            get {
                return ResourceManager.GetString("NetConnectionStatus0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connecting.
        /// </summary>
        internal static string NetConnectionStatus1 {
            get {
                return ResourceManager.GetString("NetConnectionStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authentication failed.
        /// </summary>
        internal static string NetConnectionStatus10 {
            get {
                return ResourceManager.GetString("NetConnectionStatus10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid address.
        /// </summary>
        internal static string NetConnectionStatus11 {
            get {
                return ResourceManager.GetString("NetConnectionStatus11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Credentials required.
        /// </summary>
        internal static string NetConnectionStatus12 {
            get {
                return ResourceManager.GetString("NetConnectionStatus12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connected.
        /// </summary>
        internal static string NetConnectionStatus2 {
            get {
                return ResourceManager.GetString("NetConnectionStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disconnecting.
        /// </summary>
        internal static string NetConnectionStatus3 {
            get {
                return ResourceManager.GetString("NetConnectionStatus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware not present.
        /// </summary>
        internal static string NetConnectionStatus4 {
            get {
                return ResourceManager.GetString("NetConnectionStatus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware disabled.
        /// </summary>
        internal static string NetConnectionStatus5 {
            get {
                return ResourceManager.GetString("NetConnectionStatus5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware malfunction.
        /// </summary>
        internal static string NetConnectionStatus6 {
            get {
                return ResourceManager.GetString("NetConnectionStatus6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Media disconnected.
        /// </summary>
        internal static string NetConnectionStatus7 {
            get {
                return ResourceManager.GetString("NetConnectionStatus7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authenticating.
        /// </summary>
        internal static string NetConnectionStatus8 {
            get {
                return ResourceManager.GetString("NetConnectionStatus8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authentication succeeded.
        /// </summary>
        internal static string NetConnectionStatus9 {
            get {
                return ResourceManager.GetString("NetConnectionStatus9", resourceCulture);
            }
        }
    }
}
